# Generated by Django 3.1 on 2021-03-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='user_proflie',
            new_name='user_profile',
        ),
    ]
